version: '3.9'
services:
  human-service:
    image: human-service
    networks:
      - animal
    ports:
      - "6000:80"

  meow-service:
    image: meow-service
    networks:
      - animal
    ports:
      - "6001:80"

  animal-nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - animal
    ports:
      - "8080:80"  # Expose port 8080 on the host machine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount the custom nginx.conf
    depends_on:
      - human-service
      - meow-service

networks:
  animal:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
